ARG BASE
FROM ${BASE}

ARG LIBRARY_VERSION
RUN pip install azure-iot-hub==${LIBRARY_VERSION}

COPY container_scripts/_fetch-functions.sh /
COPY container_scripts/fetch-service-secrets.sh /
COPY python/containers/run-service.sh /
COPY python/service/* /service/
COPY python/common/* /common/
RUN pip install -e common

CMD ["/bin/bash", "/run-service.sh"]

