ARG BASE
FROM ${BASE}

ARG AZURE_IOT_SERVICE_VERSION
RUN pip install azure-iot-hub==${AZURE_IOT_SERVICE_VERSION}

COPY containers/fetch-functions.sh /
COPY containers/fetch-service-secrets.sh /
COPY containers/run-service.sh /
COPY service/* /service/
COPY common/* /common/
RUN pip install -e common

CMD ["/bin/bash", "/run-service.sh"]

