ARG BASE
FROM ${BASE}

ARG AZURE_IOT_DEVICE_VERSION
RUN pip install azure-iot-device==${AZURE_IOT_DEVICE_VERSION}

COPY device/* /device/
COPY containers/fetch-device-secrets.sh /
COPY containers/run-device.sh /

CMD ["/bin/bash", "/run-device.sh"]

