ARG BASE=python:3.8.5-windowsservercore-1809
FROM ${BASE}

COPY python/device/requirements.txt \requirements-device.txt
COPY python/service/requirements.txt \requirements-service.txt

RUN pip install -r \requirements-device.txt \
    && pip install -r \requirements-service.txt \
    && pip uninstall -y azure-iot-device azure-iot-hub




